version: '2.2'
services:
    
  mongodb:
    build: ./Docker/db
    container_name: db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null