version: '2.2'
services:

  myapp:
    build: './app/Dockerfile'
    container_name:  "myapp"
    image: node:9.3.0
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
      
  mongodb:
    build: './db/Dockerfile'
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null